user_name = input('Enter your name: ')
noun = input('Enter a noun: ')
city = input('Enter a city: ')
sport = input('Enter a sport: ')
action = input('Enter a violent action: ') 
illegal_activity = input('Enter an illegal activity: ')
outside_place = input('Enter an outside location: ')
drink = input('Enter your favorite drink: ')
food = input("Enter your favorite food")

print("The backwards world of " + user_name + "|" + user_name[::-1])
print("Back in the day when I played " + sport + " on the streets of " + city.capitalize() + ", I was only six years old.")
print("I didn't like any trouble so when I wasn't playing " + sport + ", I was doing " + action + " at the " + outside_place + " with my friends.")
print("My mom didn't like me spending so much time at the " + outside_place + " because she thought I was wasting my time on useless activities")
print("Mom thought it would be a more constructive use of time if I spent my free time " + illegal_activity +".")
print("She said if I finally made money she wouldn't have to spend all our extra cash buying me my " + food + " or my precious " + drink)